[package]
name = "serde-spdx"
version = "0.8.4"
authors = ["Paul Sastrasinh <psastras@gmail.com>"]
edition = "2018"
description = "Serde serialization for SPDX files"
license = "MIT"
readme = "README.md"
keywords = ["spdx", "sbom", "serde", "serialization"]
categories = ["encoding"]
build = "build.rs"
homepage  = "https://github.com/psastras/sbom-rs"
documentation = "https://docs.rs/serde_spdx"
repository = "https://github.com/psastras/sbom-rs"

[badges]
github = { repository = "psastras/cargo-sbom" }

[features]
default = []

[dependencies]
anyhow = "1.0.71"
derive_builder = "0.12.0"
serde = "1.0.160"
serde_json = "1.0.102"
thiserror = "1.0.40"

[build-dependencies]
anyhow = "1.0.70"
prettyplease = "0.2.10"
proc-macro2 = "1.0.64"
quote = "1.0.23"
schemafy_lib = "0.6.0"
serde_json = "1.0.102"
syn = "1.0.109"
