[package]
name = "serde-cyclonedx"
version = "0.1.0"
authors = ["Paul Sastrasinh <psastras@gmail.com>"]
edition = "2018"
description = "Serde serialization for CycloneDx files"
license = "MIT"
readme = "README.md"
keywords = ["cyclonedx", "sbom", "serde", "serialization"]
categories = ["encoding"]
build = "build.rs"
homepage  = "https://github.com/psastras/sbom-rs"
documentation = "https://docs.rs/serde_cyclonedx"
repository = "https://github.com/psastras/sbom-rs"

[badges]
github = { repository = "psastras/sbom-rs" }

[features]
default = []

[dependencies]
anyhow = "1.0.71"
derive_builder = "0.12.0"
serde = "1.0.160"
serde_json = "1.0.96"
thiserror = "1.0.40"

[build-dependencies]
anyhow = "1.0.70"
prettyplease = "0.1.24"
proc-macro2 = "1.0.56"
quote = "1.0.23"
schemafy_lib = "0.6.0"
serde_json = "1.0.96"
syn = "1.0.109"
